#!/bin/bash

# Add atom repo
sudo add-apt-repository ppa:webupd8team/atom

# Update repos
sudo apt-get update --yes
sudo apt-get upgrade --yes

# Dependencies
sudo apt-get install build-essential cmake libpq-dev python-setuptools python3-setuptools python3-pip python-dev r-base vim curl openssl libssl-dev python-pip npm atom tidy postgresql postgresql-contrib zsh --yes

# Install oh-my-zsh
curl -L http://install.ohmyz.sh > install.sh
sudo sh install.sh
# chsh -s $(which zsh) $(whoami)

# Update packages
sudo pip install --upgrade pip
sudo pip install --upgrade virtualenv
sudo pip install --user virtualenvwrapper
sudo pip install autopep8
sudo pip install jsbeautifier
sudo pip install pylama
sudo pip install pylama-pylint
sudo pip install matplotlib


# Fix links to nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node
